version: '3.8'
name: tefas

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=tefas
      - POSTGRES_PASSWORD=tefas
      - POSTGRES_DB=tefas_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - my-net

  tefas:
    image: tefas:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tefas
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR.UTF-8
      - LC_ALL=tr_TR.UTF-8
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=tefas_db
      - POSTGRES_USER=tefas
      - POSTGRES_PASSWORD=tefas
    depends_on:
      - postgres_db
    networks:
      - my-net
    volumes:
      - .:/app
    command: ["streamlit", "run", "app.py", "--server.port=5002", "--server.address=0.0.0.0", "--server.enableCORS=false", "--server.enableXsrfProtection=false"]

networks:
  my-net:
    driver: bridge

volumes:
  pgdata:
